name: Build Shared Library

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create a Release
        id: create_release
        uses: shogo82148/actions-create-release@v1

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Build Shared Library for Linux
        run: GOOS=linux GOARCH=amd64 go build -o noscrape_linux_amd64 -buildmode=c-shared .

      - name: Archive Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: noscrape_linux_amd64
          path: noscrape_linux_amd64

      - name: Upload Assets
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: noscrape_linux_amd64