name: Build Shared Library

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Build Shared Library for Linux
        run: GOOS=linux GOARCH=amd64 go build -o noscrape_linux_amd64 -buildmode=c-shared .

      - name: Build Shared Library for Windows
        run: CGO_ENABLED=1 GOOS=windows GOARCH=amd64 go build -o noscrape_windows_amd64.exe -buildmode=c-shared .

      - name: Build Shared Library for macOS
        run: CGO_ENABLED=1 GOOS=darwin GOARCH=amd64 go build -o noscrape_darwin_amd64 -buildmode=c-shared .

      - name: Test
        run: go test ./...

      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: shared-library
          path: |
            noscrape_linux_amd64
            noscrape_windows_amd64.exe
            noscrape_darwin_amd64
