on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: release
    strategy:
      matrix:
        arch: [ arm64, amd64 ]
        os: [ linux-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux
          goarch: ${{ matrix.arch }}