name: Build Shared Library

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Build Shared Library for Linux
        run: GOOS=linux GOARCH=amd64 go build -o noscrape_linux_amd64 -buildmode=c-shared .

      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: shared-library
          path: noscrape_linux_amd64
